### ISSUE TITLE
GIP can' get port 2828 if USB device is connecting

### ISSUE THREAD

**Issue by shinglyu** [Mozilla-TWQA/MozITP#51]
```
Running tests for gaiatest/tests/functional/clock/test_clock_run_stopwatch_laps.py
Using workspace for temporary data: "/home/vagrant/gaia/tests/python/gaia-ui-tests"
Profile destination is TMP
Failure during test execution.
Traceback (most recent call last):

  File "/home/vagrant/gaia/venv_gip/local/lib/python2.7/site-packages/marionette_client-2.0.0-py2.7.egg/marionette/runtests.py", line 71, in run
    runner.run_tests(tests)

  File "/home/vagrant/gaia/venv_gip/local/lib/python2.7/site-packages/marionette_client-2.0.0-py2.7.egg/marionette/runner/base.py", line 809, in run_tests
    self.start_marionette()

  File "/home/vagrant/gaia/venv_gip/local/lib/python2.7/site-packages/marionette_client-2.0.0-py2.7.egg/marionette/runner/base.py", line 754, in start_marionette
    self.marionette = self.driverclass(**self._build_kwargs())

  File "/home/vagrant/gaia/venv_gip/local/lib/python2.7/site-packages/marionette_driver-1.1.1-py2.7.egg/marionette_driver/marionette.py", line 575, in __init__
    raise errors.MarionetteException(message=ex_msg)

MarionetteException: MarionetteException: localhost:2828 is unavailable.


Connection to 127.0.0.1 closed.


vagrant@vagrant-ubuntu-trusty-64:~$ adb devices
List of devices attached 
YT9112VWLS  device

```

**Comment by shinglyu** [comment]
Closed by 066098f
